#!/bin/bash

# This bash script will run the KJTipCalculatorUITests.js test script in the Simulator.
#
# Note that there are a lot of hard-coded paths that you will need to change if not
# using the same simulator instance.

# Simulator device path
deviceId="/Users/kdj/Library/Developer/CoreSimulator/Devices/61B90E01-B984-44FF-9CD8-C67532DFBABE"

# Note: using Xcode-beta.app
templateFilePath="/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate"

targetAppName="$deviceId/data/Containers/Bundle/Application/96826763-7CE0-4B0B-AB97-9D60F07D3D6F/KJTipCalculator.app/KJTipCalculator"

scriptFilePath="$(pwd)/KJTipCalculatorUITests.js"

resultsFolderPath="/tmp/KJTipCalculatorUITestsResults"
if [[ ! -d $resultsFolderPath ]]; then mkdir -p "$resultsFolderPath"; fi

instruments -w "$deviceId" \
  -t "$templateFilePath" "$targetAppName" \
  -e UIASCRIPT "$scriptFilePath" \
  -e UIARESULTSPATH "$resultsFolderPath"

